blog/urls.py
from django.urls import path
# from . import views
from .views import ( 
    like_post,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    blog_detail
)

urlpatterns = [ 
    path('', PostListView.as_view(), name='blog-home'), 
    path('post/<int:pk>/', blog_detail, name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'), 
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'), 
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('like/<int:id>', like_post, name='like_post'), 
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
urlpatterns = [
    path("admin/", admin.site.urls), 
    path('users/', include('users.urls')),  
    path('', include('blog.urls')),

] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    image = models.ImageField( default='blog_default.png',upload_to='user_directory_path')  
    blog_view = models.IntegerField(default=0, blank=True) 
    likes = models.ManyToManyField(User, blank=True, related_name="collected_votes") 
    blog_comment = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):  
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (800, 800)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Comment(models.Model): 
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments") 
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments_user", null=True)  
    content = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.post.title}"
    
    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"pk": self.pk})
        

blog/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ('content',)

class PostUpdateForm(forms.ModelForm): 
    class Meta:
        model = Post 
        fields = ['title', 'content', 'image']      



  

blog/views.py
from django.shortcuts import render, get_object_or_404 ,redirect
from .models import Post, Comment
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
) 
from .forms import CommentForm, PostUpdateForm
from django.contrib.auth.decorators import login_required


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context) 


def like_post(request, id):
    # print(id)
    if request.method == "POST":
        instance = Post.objects.get(id=id)
        # print(instance)
        if not instance.likes.filter(id=request.user.id).exists():
            instance.likes.add(request.user) 
            instance.save()
            return render(request, 'blog/likes_area.html', context={'post': instance})
        else:
            instance.likes.remove(request.user)
            instance.save()
            return render(request, 'blog/likes_area.html', context={'post': instance})


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']



class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'image']

    def form_valid(self, form):
        # for author id
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    # ? view count part
    def get_object(self,):
        views = super().get_object()
        views.blog_view += 1
        views.save()

        return views

    def get_object_like(self, *args, **kwargs):
        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()

        return total_likes

@login_required
def blog_detail(request, pk):
    post = Post.objects.get(id=pk) 
    form = CommentForm()
    form_blog= PostUpdateForm()
    comments = Comment.objects.filter(post=post.id)
    post.blog_view += 1
    post.save()  
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid(): 
            comment = form.save(commit=False)
            comment.post = post
            post.blog_comment +=1 
            comment.user = request.user
            post.blog_view -= 2
            post.save()
            comment.save()
            return redirect("post-detail", pk)
    return render(request, 'blog/post_detail.html', {'post': post, 'form': form, 'comments': comments})
 

blog/templates/blog/home.html
{% extends "templates/base.html" %}
{% load static %}
{% block content %}
<div class="contain">
  {% for post in posts %}

  <div class="cardContainer" style="background-image: url( {{post.image.url}}  ); ">
    <div class="blog__date">
      <small class="">{{ post.date_posted|date:"F d, Y" }}</small>
    </div>
    {% comment %} !!!! {% endcomment %}

    <div class="blog__info">
      <div class="counters">
        <span><i class="fas fa-eye me-1"></i>{{post.blog_view}}</span>
        <span>
          <a class="text-light bg-transparent border-0 mt-1" href="{% url 'post-detail' post.pk %}">
            <i class="fas fa-comment-alt  me-1"></i></a> 
          </i>{{post.blog_comment}}</span>
        <span> 
          {% include "blog/likes_area.html" %} 
        </span>
      </div>
      
    </div>
    {% comment %} !!!! {% endcomment %}
    <div class="blog__profile">
      <img src="{{ post.author.userprofile.image.url }}" alt="author" />
      <div class="blog__profile__text">
        <h2>
          <a class="article-title" href="{% url 'post-detail' post.pk %}">{{ post.title }}</a>
        </h2>
        <p>@<b>{{ post.author }}</b></p>
        <p class="cont">{{ post.content | truncatechars:30 }}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>





{% endblock content %}

blog/templates/blog/likes_area.html
{% if request.user.is_authenticated %}
<div
  class="list-group list-group-horizontal btn-group"
  id="likesarea{{post.id}}"
  role="group"
>
  {% csrf_token %}
  <button
    hx-post="{% url 'like_post' post.id %}"
    id="like-button"
    hx-target="#likesarea{{post.id}}"
    hx-swap="outerHTML"
    style="background-color: transparent; border: none"
    class="text-light p-0"
  > 
  
    {% if request.user in post.likes.all %}
    <i class="fa-solid fa-heart" style="color: crimson"></i>
    {% else %}
    <i class="fa-solid fa-heart" style="color: white"></i>
    {% endif %} {{post.likes.count}}
  </button>
</div>
{% else %}
<a class="  " href="{% url 'user_login' %}">
  <i class="fa-solid fa-heart text-light me-1"></i>
</a>
{{post.likes.count}} {% endif %}

blog/templates/blog/post_confirm_delete.html
{% extends "templates/base.html" %}
{% block content %} 
    <div class="container col-md-6">
        <div class="content-section ">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Delete Post</legend>
                        <h4>Are you sure you want to delete the post "{{ object.title }}" ?</h4>
                    </fieldset>
                    <div class="form-group mt-4 d-flex justify-content-between">
                        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                        <a class="btn btn-outline-success" href="{% url 'post-detail' object.id %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div> 
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "templates/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="containerDetails">
  <div class="cardContainer">
    <div class="title">
      <h2>──── Details ────</h2>
      <img src="{{ post.image.url }}" alt="poster" />
    </div>
    <div class="description">
      <h3>{{ post.title }}</h3>
      <h6>{{ post.date_posted|date:"F d, Y" }}</h6>
      <p>{{ post.content }}</p>
    </div>
    {% comment %} ! btnContainers {% endcomment %}
    <div class="cardFooter">
      <div>@{{ post.author }}</div>
      <div class="btnContainer">

        {% comment %} ! counters {% endcomment %}
        <div class="info__counter">
          <div class="counters">
            <span><i class="fas fa-eye "></i>{{post.blog_view}}</span>
            <span> <i class="fas fa-comment-alt mt-1"></i>{{post.blog_comment}}</span>
            <span>{% include "blog/likes_area.html" %}</span>
          </div>
        </div>
        {% comment %} ! counters {% endcomment %}
      </div>
    </div>
    {% comment %} ! btnContainers {% endcomment %}

    <div class="commentSection">
      
      {% if post.author == user %}
      <div class="  d-flex  flex-row-reverse ">
        <a class="btn btn-danger btn-sm  ms-2" href="{% url 'post-delete' post.id %}">
          DELETE
          {% comment %} <i class="fa-solid fa-trash"></i> {% endcomment %}
        </a>
        <a class="btn btn-secondary btn-sm  " href="{% url 'post-update' post.id %}">
          {% comment %} <i class="fa-solid fa-pen"></i>  {% endcomment %}
           UPDATE
        </a>
      </div>
      <hr>
      {% endif %}
      <form action="" method="POST">
        {% csrf_token %}
        <textarea required name="content" class="form-control" id="{{post.user.id}}" value=""
          placeholder="Leave a comment here" ></textarea>
        <div class=" w-100 d-flex flex-row-reverse"> 
          <button type="submit" class="btn btn-success mt-2 ">Comment</button>
        </div>
        
      </form>

      {% if not post.comments.all %}
      
      <div class="mt-2 ">
        <h3 class="text-light" >No comment yet...</h3>
      </div> 
      
      {% else %}
      <div class="">
        <h3 class="text-light">Comments...</h3>
        <hr>
        {% for comment in post.comments.all %}
        <div class='border rounded p-2 pb-0 mb-2 mt-2 commentsFor'>
          <div class='border-bottom border-secondary d-flex justify-content-between'>
            <p>@{{comment.user}}<sup> - {{comment.date_added |timesince}} ago</sup></p> 
          </div>
          <div>

            <p>{{comment.content}}</p>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>


  </div>
</div>


</div>
{% endblock content %}















{% comment %} <form action="" method="POST">
  {% csrf_token %}
  <textarea required name="content" class="form-control" id="{{post.user.id}}" {% if not post.comments.all %}
    placeholder="No comment yet... add one">
    </textarea>
  {% else %}
  placeholder="Leave a comment here" >
  </textarea>
  {% endif %}

  <button type="submit" class="btn btn-success mt-2">Add</button>
  <hr>
</form> {% endcomment %}

blog/templates/blog/post_form.html
{% extends "templates/base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %} 
{% block content %} 
    <div class="newBlog">
        <div class="contactForm">
          <h2 class="text-light"> Create a Post</h2>
          <div>
            <form method="POST" enctype="multipart/form-data" class="blogForm">
                {% csrf_token %}
                <div class="w-100"> 
                  <label  >Title</label>
                  {% render_field form.title placeholder="Title "  %} 
                </div>
                <div class="w-100"> 
                  <label >Content</label>
                  {% render_field form.content placeholder="Content here"  %} 
                </div> 
                <div  class="w-100 text-light "> 
                <label for="formFile" class="form-label ">Image</label>
                {% render_field form.image class='form-control' id="formFile" name="image"%}
               </div>
              <button  value="submit"  >  
                Send
              </button>
            </form>
          </div>
        </div>
      </div>
{% endblock content %}


  
{% comment %} {{form.title|as_crispy_field}} 
{{form.content|as_crispy_field}}  {% endcomment %}
{% comment %} {{ form.title.label_tag }} 
<input type="text" name="title" maxlength="100" class="textinput  " required  id="id_title">
{{ form.content.label_tag }} 
<textarea name="content" cols="40" rows="10" class="textarea form-control" required="" id="id_content"></textarea>{% endcomment %}
{% comment %} <fieldset class="form-groups ">  {% endcomment %}
    {% comment %} {{ form|crispy }} {% endcomment %}
    {% comment %} {{form.title|as_crispy_field}} {% endcomment %}
{% comment %} </fieldset> {% endcomment %}